[fcgi-program:asgi_uvicorn]
user=root
socket=unix:///tmp/server.socket.sock
directory=/www
command=uv run main.py
;当 numprocs 为1时,process_name=%(program_name)s
;当 numprocs >=2时,process_name=%(program_name)s_%(process_num)02d
process_name=%(program_name)s
;进程数量
numprocs=1
autostart=true
autorestart=true
stdout_logfile=/dev/null
redirect_stderr=true
